baseURL = "https://emrekarahan.com.tr/"
languageCode = "tr-TR"
title = "Emre'nin Blogu"
enableRobotsTXT = true
pagination.pagerSize = 10

theme = "hugo-theme-terminal"

[markup.goldmark.renderer]
  unsafe = true

[params]
  author = "Emre"
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false
